name: Debug

on:
  push:
    branches:
      - '*'

jobs:
  debug:
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #python -m pip install --upgrade pipenv==2022.10.4

      - name: debug
        run: |
          pip install "urllib3<2" vcrpy
          pip freeze | grep urllib
          pip freeze | grep vcr
          echo "Importing urllib3"
          python -c "import urllib3 ; print(urllib3.__version__)"
          echo "Importing vcr"
          python -c "import vcr"
