name: sub_workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  single-build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          mkdir dir1 dir2
          echo "Hello" > dir1/hello
          echo "World" > dir2/world
          echo $SECRET_VAR | sha256sum > dir2/secret
        shell: bash
        env:
          SECRET_VAR: ${{ secrets.SECRET_VAR }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: single
          path: |
            dir1
            dir2

  matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - name: build
        run: |
          mkdir matrix
          echo "Hello from ${{ matrix.os }}" > matrix/hello-${{ matrix.os }}
          echo "World from ${{ matrix.os }}" > matrix/world-${{ matrix.os }}
        shell: bash

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: workflow-${{ matrix.os }}
          path: |
            matrix/*-*
