name: tools, test presence and version of tools

on:
  push:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-2022

    steps:
      - name: signtool
        run: ls "c:/Program Files (x86)/Windows Kits/"10/bin/*/x86/signtool.exe
        shell: bash
