name: workflow_caller

on:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/sub_workflow.yml
    secrets: inherit

  assemble:
    needs:
      - call
    runs-on: ubuntu-latest
    steps:
      - name: download from single
        uses: actions/download-artifact@v4
        with:
          name: single

      - name: list
        run: |
          tree

      - name: download from matrix
        uses: actions/download-artifact@v4
        with:
          pattern: workflow-*
          path: matrix
          merge-multiple: true

      - name: list
        run: |
          tree
